Umbynos/uniform test.yml
arduino/arduino-create-agent pull request #578
Opened 2020-12-14 17:03 UTC by umbynos

**Please check if the PR fulfills these requirements**

- [X] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-create-agent/pulls)
      before creating one)

* **What kind of change does this PR introduce?**

CI
- **What is the current behavior?**

* **What is the new behavior?**

Allign `test.yml` to `release.yml` and add again upload artifacts: It's really useful to have a reproducible environment to compile the code for every platform.
- **Does this PR introduce a breaking change?**

no
* **Other information**:

- [X] uniform `test.yml` to `release.yml` https://github.com/arduino/arduino-create-agent/pull/576
- [X] add again upload artifacts to have a place where you can download binaries compiled on various os with the same procedure as the release (https://github.com/arduino/arduino-create-agent/pull/561)

2020-12-14 18:50 UTC, zmoog requested changes
We should update the macOS min version using the cgo and linker options.

2020-12-14 18:59 UTC, umbynos commented on .github/workflows/test.yml
> +        if: matrix.operating-system == 'macos-10.15'
:checkered_flag:

2020-12-15 12:03 UTC, zmoog approved these changes
LGTM!

2020-12-17 15:34 UTC, umbynos commented on .github/workflows/release.yml
> -        operating-system: [ubuntu-18.04, windows-2019, macos-10.15]
https://github.community/t/create-matrix-with-multiple-os-and-env-for-each-one/16895

2020-12-17 16:29 UTC, zmoog approved these changes
L(F)GTM!

2020-12-17 16:30 UTC, zmoog approved these changes
LGTM

2020-12-17 16:44 UTC, merged