the folder could exist but could be empty. It's better to check this way
arduino/arduino-create-agent pull request #797
Opened 2023-06-06 10:35 UTC by umbynos

**Please check if the PR fulfills these requirements**

- [X] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-create-agent/pulls)
      before creating one)
- [ ] Tests for the changes have been added (for bug fixes / features)

* **What kind of change does this PR introduce?**

bug fix

- **What is the current behavior?**

when uninstalling an old version of the agent (e.g. 1.2.7) a folder in `~/Applications/ArduinoCreateAgent` could be left behind (empty, but existing), after uninstalling.
This will trigger this error when running a new agent:

![image](https://github.com/arduino/arduino-create-agent/assets/34278123/32f89e1f-e6a2-47d4-b531-e4be07191b17)

* **What is the new behavior?**

The check in the new agent is performed on the content of the folder and not on the existence of the folder itself

- **Does this PR introduce a breaking change?**

no
* **Other information**:

Partially fixes #795

2023-06-06 12:37 UTC, umbynos commented
test release [here](https://github.com/arduino/arduino-create-agent/releases/tag/1.3.2)

2023-06-08 13:36 UTC, cmaglie requested changes

2023-06-08 13:36 UTC, cmaglie commented on main.go
> +	return oldFiles.Len() != 0
I'd check for the existence of the directory: `~/Applications/ArduinoCreateAgent/ArduinoCreateAgent.app`

2023-06-09 15:04 UTC, cmaglie approved these changes

2023-06-09 15:13 UTC, merged