Download the correct tools for Windows 64-bit
arduino/arduino-create-agent pull request #813
Opened 2023-08-22 15:39 UTC by MatteoPologruto

**Please check if the PR fulfills these requirements**

- [ ] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-create-agent/pulls)
      before creating one)
- [ ] Tests for the changes have been added (for bug fixes / features)

* **What kind of change does this PR introduce?**
Bug fix

- **What is the current behavior?**
Tools for Windows 32-bit are downloaded when the OS/Arch is Windows 64-bit.

* **What is the new behavior?**
The correct tools are downloaded for Windows 64-bit.

- **Does this PR introduce a breaking change?**
No

2023-08-22 15:55 UTC, cmaglie requested changes

2023-08-22 15:55 UTC, cmaglie commented on tools/download_test.go
> +		{"windows", "amd64", "x86_64-mingw32"},
The Windows 32 version must be downloaded if the Windows 64 is missing.

We could implement a compatibility logic similar to the CLI:
https://github.com/arduino/arduino-cli/blob/master/arduino/cores/tools.go#L129-L216

I don't know how much work is to import directly `cores.Tools` from arduino-cli (so we can implement the same logic also for macosx), probably it's not worth it...

Anyway, IMHO, at least the compatibility rule for Windows 64 -> Windows 32 must be implemented.

2023-08-23 13:14 UTC, umbynos commented on tools/download_test.go
I would also add a test to see if the correct tool is downloaded with the other os/arch combo

2023-08-23 13:16 UTC, umbynos commented on tools/testdata/test_tool_index.json
>          }
[This](https://github.com/arduino/arduino-create-agent/pull/813/commits/2617f628f2985b1f22fd1b02593aa2f09e0d44da?diff=split&w=1#r1303003224) could be done by adding here another version of the tool with all the os/arch available and trying to download it

2023-08-23 13:52 UTC, umbynos commented
Also I would aim to remove completely the `smetrics.Jaro(...)` approach in favour of the CLI one:
- https://github.com/MatteoPologruto/arduino-create-agent/blob/2617f628f2985b1f22fd1b02593aa2f09e0d44da/v2/pkgs/tools.go#L253
- https://github.com/MatteoPologruto/arduino-create-agent/blob/2617f628f2985b1f22fd1b02593aa2f09e0d44da/tools/tools.go#L109

2023-08-30 10:43 UTC, umbynos approved these changes

2023-08-30 10:47 UTC, cmaglie approved these changes

2023-08-30 10:49 UTC, merged